name: Life
options:
  bundleIdPrefix: tw.iwi
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"

settings:
  base:
    DEVELOPMENT_TEAM: V6T9TGS4ET
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 4

configs:
  Local: debug
  Beta: release
  Prod: release

targets:
  Life:
    type: application
    platform: iOS
    sources:
      - Life
      - Shared
    entitlements:
      path: Life/Life.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    info:
      path: Life/Info.plist
      properties:
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSLocationWhenInUseUsageDescription: "用於記錄開銷的發生地點"
        NSCameraUsageDescription: "用於掃描帳本邀請碼 QR Code 及拍攝大頭照"
        NSPhotoLibraryUsageDescription: "用於選擇大頭照"
        NSAppTransportSecurity:
          NSExceptionDomains:
            local-api-life.iwi.tw:
              NSExceptionAllowsInsecureHTTPLoads: true
    settings:
      base:
        SWIFT_EMIT_LOC_STRINGS: true
      configs:
        Local:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life.local
          PRODUCT_NAME: "Life α"
        Beta:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life.beta
          PRODUCT_NAME: "Life β"
        Prod:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life
          PRODUCT_NAME: Life
    configFiles:
      Local: Config/Local.xcconfig
      Beta: Config/Beta.xcconfig
      Prod: Config/Prod.xcconfig
    dependencies:
      - target: LifeWidget
      - target: LifeWatch

  LifeWatch:
    type: application
    platform: watchOS
    sources:
      - LifeWatch
      - Shared
    configFiles:
      Local: Config/Local.xcconfig
      Beta: Config/Beta.xcconfig
      Prod: Config/Prod.xcconfig
    info:
      path: LifeWatch/Info.plist
      properties:
        WKApplication: true
        NSLocationWhenInUseUsageDescription: "用於記錄開銷的發生地點"
        NSAppTransportSecurity:
          NSExceptionDomains:
            local-api-life.iwi.tw:
              NSExceptionAllowsInsecureHTTPLoads: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
      configs:
        Local:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life.local.watch
          INFOPLIST_KEY_CFBundleDisplayName: "Life α Watch"
          INFOPLIST_KEY_WKCompanionAppBundleIdentifier: tw.iwi.life.local
        Beta:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life.beta.watch
          INFOPLIST_KEY_CFBundleDisplayName: "Life β Watch"
          INFOPLIST_KEY_WKCompanionAppBundleIdentifier: tw.iwi.life.beta
        Prod:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life.watch
          INFOPLIST_KEY_CFBundleDisplayName: "Life Watch"
          INFOPLIST_KEY_WKCompanionAppBundleIdentifier: tw.iwi.life

  LifeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - LifeUITests
      - path: Shared/Identifiers.swift
        buildPhase: sources
    dependencies:
      - target: Life
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG LOCAL

  LifeWidget:
    type: app-extension
    platform: iOS
    sources: LifeWidget
    info:
      path: LifeWidget/Info.plist
      properties:
        CFBundleDisplayName: Life Widget
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      configs:
        Local:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life.local.widget
          INFOPLIST_KEY_CFBundleDisplayName: "Life α Widget"
        Beta:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life.beta.widget
          INFOPLIST_KEY_CFBundleDisplayName: "Life β Widget"
        Prod:
          PRODUCT_BUNDLE_IDENTIFIER: tw.iwi.life.widget
          INFOPLIST_KEY_CFBundleDisplayName: Life Widget

schemes:
  Life Local:
    build:
      targets:
        Life: all
        LifeWatch: all
        LifeWidget: all
        LifeUITests:
          - testing
    run:
      config: Local
    test:
      config: Local
      targets:
        - LifeUITests
    profile:
      config: Local
    analyze:
      config: Local

  Life Beta:
    build:
      targets:
        Life: all
        LifeWatch: all
        LifeWidget: all
    run:
      config: Beta
    archive:
      config: Beta

  Life Prod:
    build:
      targets:
        Life: all
        LifeWatch: all
        LifeWidget: all
    run:
      config: Prod
    archive:
      config: Prod

  LifeWatch Local:
    build:
      targets:
        LifeWatch: all
    run:
      config: Local

  LifeWatch Beta:
    build:
      targets:
        LifeWatch: all
    run:
      config: Beta
    archive:
      config: Beta

  LifeWatch Prod:
    build:
      targets:
        LifeWatch: all
    run:
      config: Prod
    archive:
      config: Prod
